version: "3.8"

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - ${DB_HOST}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: .
    env_file: .env
    command: >
      bash -c "wait-for-it -t 30 ${DB_HOST}:5432 &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/core
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db:
