# Generated by Django 3.1.4 on 2021-01-08 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Item')),
                ('pontos', models.IntegerField(verbose_name='Pontos')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=200, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=200, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='sobreviventes.itens')),
            ],
        ),
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Sobrevivente')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=50, verbose_name='Sexo')),
                ('infectado', models.BooleanField(default=False, verbose_name='Infectado ou Nao')),
                ('inventario', models.ManyToManyField(to='sobreviventes.Recurso', verbose_name='Inventario de Recursos')),
                ('ultimo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimo_local', to='sobreviventes.localidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sobrevivente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatoContaminacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possivel_infectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possivel_infectado', to='sobreviventes.sobrevivente')),
                ('relatado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatado_por', to='sobreviventes.sobrevivente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='relatocontaminacao',
            constraint=models.UniqueConstraint(fields=('relatado_por', 'possivel_infectado'), name='Restrição'),
        ),
    ]
